##docker-compose.yml
version : '3'
services:
  node:
    container_name: docker-node-neo4j
    restart: on-failure
    build : .
    ports:
      - '3000:3000'
    links:
      - neo4j



  neo4j:
    container_name: neo4j

    image: neo4j:3.0
    ports:
      - "17474:7474"


